services:
    # API Server - Development Mode
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        container_name: nvn-api-dev
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nvn_backend
            - REDIS_URL=redis://redis:6379
            - RABBITMQ_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
        volumes:
            - .:/app
            - /app/node_modules
            - ./logs:/app/logs
        command: ['pnpm', 'run', 'start:dev']
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

    # API Debug Mode
    api-debug:
        extends:
            service: api
        container_name: nvn-api-debug
        ports:
            - '3000:3000'
            - '9229:9229' # Debug port
        command: ['pnpm', 'run', 'start:debug']

    # PostgreSQL - Development
    postgres:
        environment:
            POSTGRES_DB: nvn_backend_dev
        volumes:
            - postgres_dev_data:/var/lib/postgresql/data
            - ./docker/postgres/init-dev.sql:/docker-entrypoint-initdb.d/init-dev.sql:ro

    # Redis - Development
    redis:
        command: redis-server --appendonly yes
        # Remove password for development

    # PgAdmin - Database Administration
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: nvn-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@nvn.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - '8080:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - nvn-network
        depends_on:
            - postgres

volumes:
    postgres_dev_data:
        driver: local
    pgadmin_data:
        driver: local
